### ISSUE TITLE
Can the new version of MatGPT streamingly receive the responses from LLM?
If not, how can we realize it?

### ISSUE THREAD

**Issue by huliangbing** [toshiakit/MatGPT#25] opened 2023-12-20 23:46 UTC

**Comment by toshiakit** [comment] 2023-12-21 12:26
This is a duplicate of #23 How to streamingly receive replies from a large model using Matlab? 
Please see my answer there.

**Comment by huliangbing** [comment] 2023-12-21 12:28
Thank you very much!
I will have a try using matlab.net.http.io.StringConsumer.

**Comment by toshiakit** [comment] 2023-12-27 18:15
This feature is added in LLMs with MATLAB.

**Comment by huliangbing** [comment] 2023-12-29 10:35
Thanks a lot!

**Comment by toshiakit** [comment] 2024-02-07 16:16
This is supported in 2.0.1

**Closed by toshiakit** 2024-02-07 16:16 UTC
Labels: duplicate, enhancement
